apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-pvc # longhorn backing pvc
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "32G" # make this 10% bigger then the workload pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      role: storage
  template:
    metadata:
      labels:
        role: storage
    spec:
      containers:
      - name: default
        image: gcr.io/google_containers/volume-nfs:0.8
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /exports
            name: vol
      volumes:
        - name: vol
          persistentVolumeClaim:
            claimName: storage-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: storage
spec:
  # hardcode a cluster ip for the service
  # so that on delete & recreate of the service the previous pv's still point
  # to this nfs-provisioner, pick a new ip for each new nfs provisioner
  clusterIP: 10.96.111.111
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    role: storage
