apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: kuohwa
  name: kuohwa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: kuohwa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default
  namespace: kuohwa
subjects:
- kind: ServiceAccount
  name: default
  namespace: kuohwa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: app-users
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kuohwa
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: kuohwa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-users
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kuohwa
subjects:
- kind: ServiceAccount
  name: default
  namespace: kuohwa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-users
