apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: debug-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 16Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: debug
  name: debug
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: debug
  template:
    metadata:
      labels:
        app: debug
    spec:
      containers:
      - name: default
        image: asia.gcr.io/kuohwa/example:develop
        imagePullPolicy: Always
        command:
          - tailf
          - /dev/null
        envFrom:
          - configMapRef:
              name: global-env
        volumeMounts:
          - name: vol
            mountPath: /data
        env: []
      volumes:
        - name: vol
          persistentVolumeClaim:
            claimName: debug-pvc
