apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oracledb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 16Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oracledb
  name: oracledb
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: oracledb
  template:
    metadata:
      labels:
        app: oracledb
    spec:
      containers:
      - name: default
        image: loliconneko/oracle-ee-11g:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: vol
            mountPath: /u01/app/oracle
        env:
          - name: WEB_CONSOLE
            value: "false"
        ports:
          - containerPort: 1521
      volumes:
        - name: vol
          persistentVolumeClaim:
            claimName: oracledb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: oracledb
spec:
  type: NodePort
  selector:
    app: oracledb
  ports:
    - protocol: TCP
      port: 1521
      targetPort: 1521
      nodePort: 30007
